### ISSUE TITLE
Error on torrent file upload when using http and udp tracker toegether.

### ISSUE THREAD

**Issue by bialy39** [KevinJDurant/OpenTorrentSite#37]
I'm trying to upload .torrent file with http:// and udp:// tracker URL and have following error:

`PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Scrapeer\socket_create() in /php/libs/scraper.php:442`
`Stack trace:`
`#0 /php/libs/scraper.php(425): Scrapeer\Scraper->udp_create_connection()`
`#1 /php/libs/scraper.php(398): Scrapeer\Scraper->prepare_udp()`
`#2 /php/libs/scraper.php(174): Scrapeer\Scraper->scrape_udp()`
`#3 /php/libs/scraper.php(101): Scrapeer\Scraper->try_scrape()`
`#4 /php/upload.php(53): Scrapeer\Scraper->scrape()`
`#5 /en/upload/upload.php(218): upload()`
`#6 {main}`
`  thrown in /php/libs/scraper.php on line 442`

This problem not appears when using separate .torrent file for http:// and separate for udp:// URL.

Regards.

**Comment by AzukaChan** [comment]
What

**Comment by AzukaChan** [comment]
What version of PHP are you using? Have you created a torrents folder in the root directory?

**Comment by bialy39** [comment]
> What version of PHP are you using? Have you created a torrents folder in the root directory?

I'm using php 7.4.
As far I remember recommended version was 7.4 but now i can see that recommended is 7.0. Something changed?
I'm going to change to 7.0 and report results.

**Comment by bialy39** [comment]
Looks like change php to 7.0 solves the problem.
Thank you!

**Comment by bialy39** [comment]
I'm sorry but I made mistake while creating .torrent file.
After change to php 7.0 error still exist:

`PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Scrapeer\socket_create() in /php/libs/scraper.php:442`
`Stack trace:`
`#0 /php/libs/scraper.php(425): Scrapeer\Scraper->udp_create_connection('c5et1k3pncit8sk...', 8000)`
`#1 /php/libs/scraper.php(398): Scrapeer\Scraper->prepare_udp('c5et1k3pncit8sk...', 8000)`
`#2 /php/libs/scraper.php(174): Scrapeer\Scraper->scrape_udp(Array, 'c5et1k3pncit8sk...', 8000, false)`
`#3 /php/libs/scraper.php(101): Scrapeer\Scraper->try_scrape('udp', 'c5et1k3pncit8sk...', 8000, '', false)`
`#4 /php/upload.php(53): Scrapeer\Scraper->scrape(Array, Array)`
`#5 /en/upload/upload.php(218): upload()`
`#6 {main}`
`  thrown in /php/libs/scraper.php on line 442`

There is exactly same error when using udp:// url only.
Please note that tracker is running on same address.

Of course torrents folder in the root directory is created.

Regards.
